# Temporal Fact States
STATE_CURRENT = "current"
STATE_STALE = "stale"
STATE_EXPIRED = "expired"
STATE_SUPERSEDED = "superseded"
STATE_ABSENT_UNCONFIRMED = "absent_unconfirmed"
STATE_ABSENT_CONFIRMED = "absent_confirmed"

# Change Types
FACT_APPEARED = "FACT_APPEARED"
FACT_VALUE_CHANGED = "FACT_VALUE_CHANGED"
FACT_BECAME_STALE = "FACT_BECAME_STALE"
FACT_EXPIRED = "FACT_EXPIRED"
FACT_ABSENCE_SUSPECTED = "FACT_ABSENCE_SUSPECTED"
FACT_DISAPPEARED = "FACT_DISAPPEARED"
FACT_REAPPEARED = "FACT_REAPPEARED"
FACT_SUPERSEDED = "FACT_SUPERSEDED"
CONTRADICTION_ADDED = "CONTRADICTION_ADDED"
CONTRADICTION_RESOLVED = "CONTRADICTION_RESOLVED"
USER_DECISION_CHANGED = "USER_DECISION_CHANGED"

# Confidence States
CONFIDENCE_OBSERVED_ONCE = "observed_once"
CONFIDENCE_REVALIDATED = "revalidated"
CONFIDENCE_CORROBORATED = "corroborated"
CONFIDENCE_OPERATIONALLY_UNCERTAIN = "operationally_uncertain"

# Materiality Levels
MATERIALITY_INFORMATIONAL = "informational"
MATERIALITY_LOW = "low"
MATERIALITY_MEDIUM = "medium"
MATERIALITY_HIGH = "high"
MATERIALITY_CRITICAL_REVIEW = "critical_review"

# Review Types
REVIEW_IDENTITY_CHANGE = "identity_change"
REVIEW_CONFLICTING_EVIDENCE = "conflicting_evidence"
REVIEW_PROFILE_AVAILABILITY_CHANGE = "profile_availability_change"
REVIEW_CONFIRMED_PROFILE_CHANGE = "confirmed_profile_change"
REVIEW_REVALIDATION_REQUIRED = "revalidation_required"

# Review Priority
PRIORITY_LOW = "low"
PRIORITY_MEDIUM = "medium"
PRIORITY_HIGH = "high"
PRIORITY_CRITICAL = "critical"

# Review Statuses
REVIEW_STATUS_OPEN = "open"
REVIEW_STATUS_IN_REVIEW = "in_review"
REVIEW_STATUS_RESOLVED = "resolved"
REVIEW_STATUS_DISMISSED = "dismissed"
REVIEW_STATUS_SUPERSEDED = "superseded"

# Review Resolutions
RESOLUTION_ACKNOWLEDGED = "ACKNOWLEDGED"
RESOLUTION_THIS_IS_STILL_MINE = "THIS_IS_STILL_MINE"
RESOLUTION_THIS_IS_NOT_MINE = "THIS_IS_NOT_MINE"
RESOLUTION_EXPECTED_CHANGE = "EXPECTED_CHANGE"
RESOLUTION_REQUEST_REVALIDATION = "REQUEST_REVALIDATION"
RESOLUTION_DISMISS_ALERT = "DISMISS_ALERT"
