"""sprint_20_orchestration

Revision ID: 11cf1eaeb4ad
Revises: b4585c600b84
Create Date: 2026-07-14 22:40:21.455890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '11cf1eaeb4ad'
down_revision: Union[str, None] = 'b4585c600b84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identity_orchestration_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('anchor_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('policy_version', sa.Integer(), nullable=False),
    sa.Column('input_fingerprint', sa.String(length=255), nullable=False),
    sa.Column('requested_capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('planned_connector_count', sa.Integer(), nullable=False),
    sa.Column('executed_connector_count', sa.Integer(), nullable=False),
    sa.Column('skipped_connector_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['anchor_id'], ['identity_anchors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identity_orchestration_runs_anchor_id'), 'identity_orchestration_runs', ['anchor_id'], unique=False)
    op.create_index(op.f('ix_identity_orchestration_runs_input_fingerprint'), 'identity_orchestration_runs', ['input_fingerprint'], unique=False)
    op.create_index(op.f('ix_identity_orchestration_runs_status'), 'identity_orchestration_runs', ['status'], unique=False)
    op.create_index(op.f('ix_identity_orchestration_runs_user_id'), 'identity_orchestration_runs', ['user_id'], unique=False)
    op.create_table('connector_execution_plan_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('orchestration_run_id', sa.UUID(), nullable=False),
    sa.Column('connector_type', sa.String(length=64), nullable=False),
    sa.Column('capability', sa.String(length=64), nullable=False),
    sa.Column('input_alias_id', sa.UUID(), nullable=True),
    sa.Column('decision', sa.String(length=64), nullable=False),
    sa.Column('decision_reason', sa.String(length=255), nullable=True),
    sa.Column('freshness_state', sa.String(length=32), nullable=True),
    sa.Column('health_state', sa.String(length=32), nullable=True),
    sa.Column('budget_state', sa.String(length=32), nullable=True),
    sa.Column('discovery_run_id', sa.UUID(), nullable=True),
    sa.Column('execution_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['discovery_run_id'], ['candidate_discovery_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['input_alias_id'], ['identity_aliases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['orchestration_run_id'], ['identity_orchestration_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connector_execution_plan_items_discovery_run_id'), 'connector_execution_plan_items', ['discovery_run_id'], unique=False)
    op.create_index(op.f('ix_connector_execution_plan_items_input_alias_id'), 'connector_execution_plan_items', ['input_alias_id'], unique=False)
    op.create_index(op.f('ix_connector_execution_plan_items_orchestration_run_id'), 'connector_execution_plan_items', ['orchestration_run_id'], unique=False)
    op.add_column('candidate_provenance_observations', sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False))
    op.add_column('candidate_provenance_observations', sa.Column('last_observed_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('candidate_provenance_observations', sa.Column('stale_after', sa.DateTime(timezone=True), nullable=True))
    op.add_column('candidate_provenance_observations', sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('candidate_provenance_observations', sa.Column('freshness_policy_version', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_provenance_observations', 'freshness_policy_version')
    op.drop_column('candidate_provenance_observations', 'superseded_at')
    op.drop_column('candidate_provenance_observations', 'stale_after')
    op.drop_column('candidate_provenance_observations', 'last_observed_at')
    op.drop_column('candidate_provenance_observations', 'valid_from')
    op.drop_index(op.f('ix_connector_execution_plan_items_orchestration_run_id'), table_name='connector_execution_plan_items')
    op.drop_index(op.f('ix_connector_execution_plan_items_input_alias_id'), table_name='connector_execution_plan_items')
    op.drop_index(op.f('ix_connector_execution_plan_items_discovery_run_id'), table_name='connector_execution_plan_items')
    op.drop_table('connector_execution_plan_items')
    op.drop_index(op.f('ix_identity_orchestration_runs_user_id'), table_name='identity_orchestration_runs')
    op.drop_index(op.f('ix_identity_orchestration_runs_status'), table_name='identity_orchestration_runs')
    op.drop_index(op.f('ix_identity_orchestration_runs_input_fingerprint'), table_name='identity_orchestration_runs')
    op.drop_index(op.f('ix_identity_orchestration_runs_anchor_id'), table_name='identity_orchestration_runs')
    op.drop_table('identity_orchestration_runs')
    # ### end Alembic commands ###
