"""Add IdentityAnchor models

Revision ID: 121d5428cc44
Revises: 56863a2cf14f
Create Date: 2026-07-14 00:44:11.169733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '121d5428cc44'
down_revision: Union[str, None] = '56863a2cf14f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identity_anchors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_identity_anchor_user')
    )
    op.create_index(op.f('ix_identity_anchors_user_id'), 'identity_anchors', ['user_id'], unique=False)
    op.create_table('confirmed_profile_references',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('anchor_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=64), nullable=False),
    sa.Column('profile_url_display', sa.String(length=1024), nullable=False),
    sa.Column('profile_url_canonical', sa.String(length=1024), nullable=False),
    sa.Column('username_hint', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('confirmation_method', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['anchor_id'], ['identity_anchors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_confirmed_profile_references_anchor_id'), 'confirmed_profile_references', ['anchor_id'], unique=False)
    op.create_index(op.f('ix_confirmed_profile_references_profile_url_canonical'), 'confirmed_profile_references', ['profile_url_canonical'], unique=False)
    op.create_index(op.f('ix_confirmed_profile_references_user_id'), 'confirmed_profile_references', ['user_id'], unique=False)
    op.create_table('identity_aliases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('anchor_id', sa.UUID(), nullable=False),
    sa.Column('alias_type', sa.String(length=32), nullable=False),
    sa.Column('value_display', sa.String(length=512), nullable=False),
    sa.Column('value_canonical', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('confirmation_method', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['anchor_id'], ['identity_anchors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identity_aliases_anchor_id'), 'identity_aliases', ['anchor_id'], unique=False)
    op.create_index(op.f('ix_identity_aliases_user_id'), 'identity_aliases', ['user_id'], unique=False)
    op.create_index(op.f('ix_identity_aliases_value_canonical'), 'identity_aliases', ['value_canonical'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_identity_aliases_value_canonical'), table_name='identity_aliases')
    op.drop_index(op.f('ix_identity_aliases_user_id'), table_name='identity_aliases')
    op.drop_index(op.f('ix_identity_aliases_anchor_id'), table_name='identity_aliases')
    op.drop_table('identity_aliases')
    op.drop_index(op.f('ix_confirmed_profile_references_user_id'), table_name='confirmed_profile_references')
    op.drop_index(op.f('ix_confirmed_profile_references_profile_url_canonical'), table_name='confirmed_profile_references')
    op.drop_index(op.f('ix_confirmed_profile_references_anchor_id'), table_name='confirmed_profile_references')
    op.drop_table('confirmed_profile_references')
    op.drop_index(op.f('ix_identity_anchors_user_id'), table_name='identity_anchors')
    op.drop_table('identity_anchors')
    # ### end Alembic commands ###
