"""Add execution_mode to provenance observations

Revision ID: 2ec027d8be5b
Revises: 7899b9e77141
Create Date: 2026-07-14 23:59:18.856637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ec027d8be5b'
down_revision: Union[str, None] = '7899b9e77141'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_provenance_observations', sa.Column('execution_mode', sa.String(length=16), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_provenance_observations', 'execution_mode')
    # ### end Alembic commands ###
