"""assessment_input_fingerprint

Revision ID: 31ae10448288
Revises: e6b4864fff3d
Create Date: 2026-07-14 22:45:39.439982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31ae10448288'
down_revision: Union[str, None] = 'e6b4864fff3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('identity_match_assessments', sa.Column('input_fingerprint', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_identity_match_assessments_input_fingerprint'), 'identity_match_assessments', ['input_fingerprint'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_identity_match_assessments_input_fingerprint'), table_name='identity_match_assessments')
    op.drop_column('identity_match_assessments', 'input_fingerprint')
    # ### end Alembic commands ###
