"""Drop unique constraint on connector_type

Revision ID: 49a9656ea2e1
Revises: 5a67882dff91
Create Date: 2026-07-15 03:17:33.666214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49a9656ea2e1'
down_revision: Union[str, None] = '5a67882dff91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_connector_certification_records_connector_type'), table_name='connector_certification_records')
    op.create_index(op.f('ix_connector_certification_records_connector_type'), 'connector_certification_records', ['connector_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_connector_certification_records_connector_type'), table_name='connector_certification_records')
    op.create_index(op.f('ix_connector_certification_records_connector_type'), 'connector_certification_records', ['connector_type'], unique=True)
    # ### end Alembic commands ###
