"""Add IdentityMatchAssessment

Revision ID: 524f042778ac
Revises: 5c9980e0d0ad
Create Date: 2026-07-14 21:37:22.793167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '524f042778ac'
down_revision: Union[str, None] = '5c9980e0d0ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identity_match_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('anchor_id', sa.UUID(), nullable=False),
    sa.Column('candidate_profile_id', sa.UUID(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('anchor_version', sa.Integer(), nullable=False),
    sa.Column('candidate_revision', sa.String(length=255), nullable=False),
    sa.Column('engine_version', sa.Integer(), nullable=False),
    sa.Column('policy_version', sa.Integer(), nullable=False),
    sa.Column('assessment_input_fingerprint', sa.String(length=255), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('assessment_status', sa.String(length=32), nullable=False),
    sa.Column('confidence_band', sa.String(length=128), nullable=False),
    sa.Column('evidence_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('explanation_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('stale_state', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['anchor_id'], ['identity_anchors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identity_match_assessments_anchor_id'), 'identity_match_assessments', ['anchor_id'], unique=False)
    op.create_index(op.f('ix_identity_match_assessments_assessment_input_fingerprint'), 'identity_match_assessments', ['assessment_input_fingerprint'], unique=False)
    op.create_index(op.f('ix_identity_match_assessments_assessment_status'), 'identity_match_assessments', ['assessment_status'], unique=False)
    op.create_index(op.f('ix_identity_match_assessments_candidate_profile_id'), 'identity_match_assessments', ['candidate_profile_id'], unique=False)
    op.create_index(op.f('ix_identity_match_assessments_is_current'), 'identity_match_assessments', ['is_current'], unique=False)
    op.create_index(op.f('ix_identity_match_assessments_user_id'), 'identity_match_assessments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_identity_match_assessments_user_id'), table_name='identity_match_assessments')
    op.drop_index(op.f('ix_identity_match_assessments_is_current'), table_name='identity_match_assessments')
    op.drop_index(op.f('ix_identity_match_assessments_candidate_profile_id'), table_name='identity_match_assessments')
    op.drop_index(op.f('ix_identity_match_assessments_assessment_status'), table_name='identity_match_assessments')
    op.drop_index(op.f('ix_identity_match_assessments_assessment_input_fingerprint'), table_name='identity_match_assessments')
    op.drop_index(op.f('ix_identity_match_assessments_anchor_id'), table_name='identity_match_assessments')
    op.drop_table('identity_match_assessments')
    # ### end Alembic commands ###
