"""Add ResidualInferenceRecord

Revision ID: 56863a2cf14f
Revises: 008_sprint8_privacy
Create Date: 2026-07-13 14:39:50.563252

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '56863a2cf14f'
down_revision: str | None = '008_sprint8_privacy'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('residual_inference_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('score_snapshot_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('feature_schema_version', sa.String(length=64), nullable=True),
    sa.Column('raw_delta', sa.Float(), nullable=True),
    sa.Column('bounded_delta', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('abstained', sa.Boolean(), nullable=False),
    sa.Column('abstention_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['score_snapshot_id'], ['score_snapshots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_residual_inference_records_created_at'), 'residual_inference_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_residual_inference_records_score_snapshot_id'), 'residual_inference_records', ['score_snapshot_id'], unique=True)
    op.create_index(op.f('ix_residual_inference_records_user_id'), 'residual_inference_records', ['user_id'], unique=False)
    op.create_index(op.f('ix_alerts_identifier_id'), 'alerts', ['identifier_id'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_broker_optout_state_identifier_id'), 'broker_optout_state', ['identifier_id'], unique=False)
    op.create_index(op.f('ix_captcha_queue_expires_at'), 'captcha_queue', ['expires_at'], unique=False)
    op.create_index(op.f('ix_captcha_queue_job_id'), 'captcha_queue', ['job_id'], unique=False)
    op.create_index(op.f('ix_captcha_queue_job_item_id'), 'captcha_queue', ['job_item_id'], unique=False)
    op.create_index(op.f('ix_data_export_jobs_expires_at'), 'data_export_jobs', ['expires_at'], unique=False)
    op.create_index(op.f('ix_evidence_blobs_observation_id'), 'evidence_blobs', ['observation_id'], unique=False)
    op.create_index(op.f('ix_freeze_checklist_items_user_id'), 'freeze_checklist_items', ['user_id'], unique=False)
    op.create_index(op.f('ix_identity_edges_left_identifier_id'), 'identity_edges', ['left_identifier_id'], unique=False)
    op.create_index(op.f('ix_identity_edges_right_identifier_id'), 'identity_edges', ['right_identifier_id'], unique=False)
    op.create_index(op.f('ix_narrative_briefings_identifier_id'), 'narrative_briefings', ['identifier_id'], unique=False)
    op.create_index(op.f('ix_narrative_briefings_score_snapshot_id'), 'narrative_briefings', ['score_snapshot_id'], unique=False)
    op.create_index(op.f('ix_observations_connector_run_id'), 'observations', ['connector_run_id'], unique=False)
    op.create_index(op.f('ix_recommendation_plans_identifier_id'), 'recommendation_plans', ['identifier_id'], unique=False)
    op.create_index(op.f('ix_recommendations_identifier_id'), 'recommendations', ['identifier_id'], unique=False)
    op.create_index(op.f('ix_remediation_job_items_broker_id'), 'remediation_job_items', ['broker_id'], unique=False)
    op.create_index(op.f('ix_remediation_job_items_user_id'), 'remediation_job_items', ['user_id'], unique=False)
    op.create_index(op.f('ix_remediation_jobs_identifier_id'), 'remediation_jobs', ['identifier_id'], unique=False)
    op.create_index(op.f('ix_scan_connector_runs_identifier_id'), 'scan_connector_runs', ['identifier_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_connector_runs_identifier_id'), table_name='scan_connector_runs')
    op.drop_index(op.f('ix_remediation_jobs_identifier_id'), table_name='remediation_jobs')
    op.drop_index(op.f('ix_remediation_job_items_user_id'), table_name='remediation_job_items')
    op.drop_index(op.f('ix_remediation_job_items_broker_id'), table_name='remediation_job_items')
    op.drop_index(op.f('ix_recommendations_identifier_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendation_plans_identifier_id'), table_name='recommendation_plans')
    op.drop_index(op.f('ix_observations_connector_run_id'), table_name='observations')
    op.drop_index(op.f('ix_narrative_briefings_score_snapshot_id'), table_name='narrative_briefings')
    op.drop_index(op.f('ix_narrative_briefings_identifier_id'), table_name='narrative_briefings')
    op.drop_index(op.f('ix_identity_edges_right_identifier_id'), table_name='identity_edges')
    op.drop_index(op.f('ix_identity_edges_left_identifier_id'), table_name='identity_edges')
    op.drop_index(op.f('ix_freeze_checklist_items_user_id'), table_name='freeze_checklist_items')
    op.drop_index(op.f('ix_evidence_blobs_observation_id'), table_name='evidence_blobs')
    op.drop_index(op.f('ix_data_export_jobs_expires_at'), table_name='data_export_jobs')
    op.drop_index(op.f('ix_captcha_queue_job_item_id'), table_name='captcha_queue')
    op.drop_index(op.f('ix_captcha_queue_job_id'), table_name='captcha_queue')
    op.drop_index(op.f('ix_captcha_queue_expires_at'), table_name='captcha_queue')
    op.drop_index(op.f('ix_broker_optout_state_identifier_id'), table_name='broker_optout_state')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_identifier_id'), table_name='alerts')
    op.drop_index(op.f('ix_residual_inference_records_user_id'), table_name='residual_inference_records')
    op.drop_index(op.f('ix_residual_inference_records_score_snapshot_id'), table_name='residual_inference_records')
    op.drop_index(op.f('ix_residual_inference_records_created_at'), table_name='residual_inference_records')
    op.drop_table('residual_inference_records')
    # ### end Alembic commands ###
