"""Add Sprint 23 certification and audit fields

Revision ID: 5a67882dff91
Revises: 2ec027d8be5b
Create Date: 2026-07-15 03:12:01.398496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a67882dff91'
down_revision: Union[str, None] = '2ec027d8be5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_provenance_observations', sa.Column('connector_certification_id', sa.UUID(), nullable=True))
    op.add_column('candidate_provenance_observations', sa.Column('runtime_fingerprint', sa.String(length=64), nullable=True))
    op.add_column('candidate_provenance_observations', sa.Column('adapter_version', sa.String(length=64), nullable=True))
    op.add_column('candidate_provenance_observations', sa.Column('runtime_version', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_candidate_provenance_observations_connector_certification_id'), 'candidate_provenance_observations', ['connector_certification_id'], unique=False)
    op.create_index(op.f('ix_candidate_provenance_observations_runtime_fingerprint'), 'candidate_provenance_observations', ['runtime_fingerprint'], unique=False)
    op.create_foreign_key(None, 'candidate_provenance_observations', 'connector_certification_records', ['connector_certification_id'], ['id'], ondelete='SET NULL')
    op.add_column('connector_certification_records', sa.Column('runtime_fingerprint', sa.String(length=64), nullable=True))
    op.add_column('connector_certification_records', sa.Column('conformance_policy_version', sa.Integer(), nullable=True))
    op.add_column('connector_certification_records', sa.Column('parser_version', sa.String(length=64), nullable=True))
    op.add_column('connector_certification_records', sa.Column('live_smoke_status', sa.String(length=32), nullable=False))
    op.add_column('connector_certification_records', sa.Column('live_smoke_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('connector_certification_records', sa.Column('invalidated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('connector_certification_records', sa.Column('invalidation_reason', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_connector_certification_records_runtime_fingerprint'), 'connector_certification_records', ['runtime_fingerprint'], unique=False)
    op.add_column('connector_execution_plan_items', sa.Column('runtime_fingerprint', sa.String(length=64), nullable=True))
    op.add_column('connector_execution_plan_items', sa.Column('certification_id', sa.UUID(), nullable=True))
    op.add_column('connector_execution_plan_items', sa.Column('execution_mode', sa.String(length=16), nullable=True))
    op.add_column('connector_execution_plan_items', sa.Column('outcome', sa.String(length=32), nullable=True))
    op.add_column('connector_execution_plan_items', sa.Column('normalized_result_count', sa.Integer(), nullable=True))
    op.add_column('connector_execution_plan_items', sa.Column('error_category', sa.String(length=32), nullable=True))
    op.add_column('connector_execution_plan_items', sa.Column('timeout_occurred', sa.Boolean(), nullable=False))
    op.add_column('connector_execution_plan_items', sa.Column('output_truncated', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_connector_execution_plan_items_certification_id'), 'connector_execution_plan_items', ['certification_id'], unique=False)
    op.create_index(op.f('ix_connector_execution_plan_items_runtime_fingerprint'), 'connector_execution_plan_items', ['runtime_fingerprint'], unique=False)
    op.create_foreign_key(None, 'connector_execution_plan_items', 'connector_certification_records', ['certification_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'connector_execution_plan_items', type_='foreignkey')
    op.drop_index(op.f('ix_connector_execution_plan_items_runtime_fingerprint'), table_name='connector_execution_plan_items')
    op.drop_index(op.f('ix_connector_execution_plan_items_certification_id'), table_name='connector_execution_plan_items')
    op.drop_column('connector_execution_plan_items', 'output_truncated')
    op.drop_column('connector_execution_plan_items', 'timeout_occurred')
    op.drop_column('connector_execution_plan_items', 'error_category')
    op.drop_column('connector_execution_plan_items', 'normalized_result_count')
    op.drop_column('connector_execution_plan_items', 'outcome')
    op.drop_column('connector_execution_plan_items', 'execution_mode')
    op.drop_column('connector_execution_plan_items', 'certification_id')
    op.drop_column('connector_execution_plan_items', 'runtime_fingerprint')
    op.drop_index(op.f('ix_connector_certification_records_runtime_fingerprint'), table_name='connector_certification_records')
    op.drop_column('connector_certification_records', 'invalidation_reason')
    op.drop_column('connector_certification_records', 'invalidated_at')
    op.drop_column('connector_certification_records', 'live_smoke_at')
    op.drop_column('connector_certification_records', 'live_smoke_status')
    op.drop_column('connector_certification_records', 'parser_version')
    op.drop_column('connector_certification_records', 'conformance_policy_version')
    op.drop_column('connector_certification_records', 'runtime_fingerprint')
    op.drop_constraint(None, 'candidate_provenance_observations', type_='foreignkey')
    op.drop_index(op.f('ix_candidate_provenance_observations_runtime_fingerprint'), table_name='candidate_provenance_observations')
    op.drop_index(op.f('ix_candidate_provenance_observations_connector_certification_id'), table_name='candidate_provenance_observations')
    op.drop_column('candidate_provenance_observations', 'runtime_version')
    op.drop_column('candidate_provenance_observations', 'adapter_version')
    op.drop_column('candidate_provenance_observations', 'runtime_fingerprint')
    op.drop_column('candidate_provenance_observations', 'connector_certification_id')
    # ### end Alembic commands ###
