"""Add Candidate Discovery models

Revision ID: 5c9980e0d0ad
Revises: 121d5428cc44
Create Date: 2026-07-14 01:10:28.114311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c9980e0d0ad'
down_revision: Union[str, None] = '121d5428cc44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_discovery_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('anchor_id', sa.UUID(), nullable=False),
    sa.Column('anchor_version', sa.Integer(), nullable=False),
    sa.Column('source_tool', sa.String(length=64), nullable=False),
    sa.Column('source_tool_version', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('input_count', sa.Integer(), nullable=False),
    sa.Column('candidate_count', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['anchor_id'], ['identity_anchors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_discovery_runs_anchor_id'), 'candidate_discovery_runs', ['anchor_id'], unique=False)
    op.create_index(op.f('ix_candidate_discovery_runs_status'), 'candidate_discovery_runs', ['status'], unique=False)
    op.create_index(op.f('ix_candidate_discovery_runs_user_id'), 'candidate_discovery_runs', ['user_id'], unique=False)
    op.create_table('candidate_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('discovery_run_id', sa.UUID(), nullable=False),
    sa.Column('anchor_id', sa.UUID(), nullable=False),
    sa.Column('anchor_version', sa.Integer(), nullable=False),
    sa.Column('source_input_id', sa.UUID(), nullable=False),
    sa.Column('source_input_type', sa.String(length=64), nullable=False),
    sa.Column('source_input_value_reference', sa.String(length=512), nullable=False),
    sa.Column('platform', sa.String(length=64), nullable=False),
    sa.Column('profile_url', sa.String(length=1024), nullable=False),
    sa.Column('canonical_profile_url', sa.String(length=1024), nullable=False),
    sa.Column('username_observed', sa.String(length=255), nullable=False),
    sa.Column('display_name_observed', sa.String(length=512), nullable=True),
    sa.Column('candidate_status', sa.String(length=32), nullable=False),
    sa.Column('source_tool', sa.String(length=64), nullable=False),
    sa.Column('source_tool_version', sa.String(length=64), nullable=False),
    sa.Column('first_observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['anchor_id'], ['identity_anchors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['discovery_run_id'], ['candidate_discovery_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_profiles_anchor_id'), 'candidate_profiles', ['anchor_id'], unique=False)
    op.create_index(op.f('ix_candidate_profiles_candidate_status'), 'candidate_profiles', ['candidate_status'], unique=False)
    op.create_index(op.f('ix_candidate_profiles_canonical_profile_url'), 'candidate_profiles', ['canonical_profile_url'], unique=False)
    op.create_index(op.f('ix_candidate_profiles_discovery_run_id'), 'candidate_profiles', ['discovery_run_id'], unique=False)
    op.create_index(op.f('ix_candidate_profiles_source_input_id'), 'candidate_profiles', ['source_input_id'], unique=False)
    op.create_index(op.f('ix_candidate_profiles_user_id'), 'candidate_profiles', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidate_profiles_user_id'), table_name='candidate_profiles')
    op.drop_index(op.f('ix_candidate_profiles_source_input_id'), table_name='candidate_profiles')
    op.drop_index(op.f('ix_candidate_profiles_discovery_run_id'), table_name='candidate_profiles')
    op.drop_index(op.f('ix_candidate_profiles_canonical_profile_url'), table_name='candidate_profiles')
    op.drop_index(op.f('ix_candidate_profiles_candidate_status'), table_name='candidate_profiles')
    op.drop_index(op.f('ix_candidate_profiles_anchor_id'), table_name='candidate_profiles')
    op.drop_table('candidate_profiles')
    op.drop_index(op.f('ix_candidate_discovery_runs_user_id'), table_name='candidate_discovery_runs')
    op.drop_index(op.f('ix_candidate_discovery_runs_status'), table_name='candidate_discovery_runs')
    op.drop_index(op.f('ix_candidate_discovery_runs_anchor_id'), table_name='candidate_discovery_runs')
    op.drop_table('candidate_discovery_runs')
    # ### end Alembic commands ###
