"""Add ConnectorCertificationRecord

Revision ID: 7899b9e77141
Revises: a5857207f85b
Create Date: 2026-07-14 23:47:04.120430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7899b9e77141'
down_revision: Union[str, None] = 'a5857207f85b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connector_certification_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('connector_type', sa.String(length=64), nullable=False),
    sa.Column('availability', sa.String(length=32), nullable=False),
    sa.Column('adapter_version', sa.String(length=64), nullable=False),
    sa.Column('runtime_version', sa.String(length=64), nullable=True),
    sa.Column('runtime_revision', sa.String(length=64), nullable=True),
    sa.Column('last_certified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_health_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('certification_details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connector_certification_records_connector_type'), 'connector_certification_records', ['connector_type'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_connector_certification_records_connector_type'), table_name='connector_certification_records')
    op.drop_table('connector_certification_records')
    # ### end Alembic commands ###
