"""Sprint 21 temporal evidence and review queue

Revision ID: a5857207f85b
Revises: 31ae10448288
Create Date: 2026-07-14 23:10:37.997464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5857207f85b'
down_revision: Union[str, None] = '31ae10448288'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identity_change_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('anchor_id', sa.UUID(), nullable=False),
    sa.Column('candidate_profile_id', sa.UUID(), nullable=True),
    sa.Column('canonical_fact_key', sa.String(length=512), nullable=False),
    sa.Column('change_type', sa.String(length=64), nullable=False),
    sa.Column('previous_value_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('new_value_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('previous_state', sa.String(length=64), nullable=True),
    sa.Column('new_state', sa.String(length=64), nullable=False),
    sa.Column('materiality', sa.String(length=64), nullable=False),
    sa.Column('review_priority', sa.String(length=64), nullable=False),
    sa.Column('confidence_state', sa.String(length=64), nullable=False),
    sa.Column('event_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('change_policy_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source_observation_lineage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['anchor_id'], ['identity_anchors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identity_change_events_anchor_id'), 'identity_change_events', ['anchor_id'], unique=False)
    op.create_index(op.f('ix_identity_change_events_candidate_profile_id'), 'identity_change_events', ['candidate_profile_id'], unique=False)
    op.create_index(op.f('ix_identity_change_events_canonical_fact_key'), 'identity_change_events', ['canonical_fact_key'], unique=False)
    op.create_index(op.f('ix_identity_change_events_detected_at'), 'identity_change_events', ['detected_at'], unique=False)
    op.create_index(op.f('ix_identity_change_events_event_fingerprint'), 'identity_change_events', ['event_fingerprint'], unique=True)
    op.create_index(op.f('ix_identity_change_events_user_id'), 'identity_change_events', ['user_id'], unique=False)
    op.create_table('identity_review_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('anchor_id', sa.UUID(), nullable=False),
    sa.Column('candidate_profile_id', sa.UUID(), nullable=True),
    sa.Column('review_type', sa.String(length=64), nullable=False),
    sa.Column('priority', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reason_code', sa.String(length=128), nullable=False),
    sa.Column('grouping_key', sa.String(length=128), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('resolution', sa.String(length=64), nullable=True),
    sa.Column('resolution_note', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['anchor_id'], ['identity_anchors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identity_review_items_anchor_id'), 'identity_review_items', ['anchor_id'], unique=False)
    op.create_index(op.f('ix_identity_review_items_candidate_profile_id'), 'identity_review_items', ['candidate_profile_id'], unique=False)
    op.create_index(op.f('ix_identity_review_items_created_at'), 'identity_review_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_identity_review_items_grouping_key'), 'identity_review_items', ['grouping_key'], unique=False)
    op.create_index(op.f('ix_identity_review_items_priority'), 'identity_review_items', ['priority'], unique=False)
    op.create_index(op.f('ix_identity_review_items_status'), 'identity_review_items', ['status'], unique=False)
    op.create_index(op.f('ix_identity_review_items_user_id'), 'identity_review_items', ['user_id'], unique=False)
    op.create_table('identity_review_item_events',
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['identity_change_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_id'], ['identity_review_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('review_id', 'event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('identity_review_item_events')
    op.drop_index(op.f('ix_identity_review_items_user_id'), table_name='identity_review_items')
    op.drop_index(op.f('ix_identity_review_items_status'), table_name='identity_review_items')
    op.drop_index(op.f('ix_identity_review_items_priority'), table_name='identity_review_items')
    op.drop_index(op.f('ix_identity_review_items_grouping_key'), table_name='identity_review_items')
    op.drop_index(op.f('ix_identity_review_items_created_at'), table_name='identity_review_items')
    op.drop_index(op.f('ix_identity_review_items_candidate_profile_id'), table_name='identity_review_items')
    op.drop_index(op.f('ix_identity_review_items_anchor_id'), table_name='identity_review_items')
    op.drop_table('identity_review_items')
    op.drop_index(op.f('ix_identity_change_events_user_id'), table_name='identity_change_events')
    op.drop_index(op.f('ix_identity_change_events_event_fingerprint'), table_name='identity_change_events')
    op.drop_index(op.f('ix_identity_change_events_detected_at'), table_name='identity_change_events')
    op.drop_index(op.f('ix_identity_change_events_canonical_fact_key'), table_name='identity_change_events')
    op.drop_index(op.f('ix_identity_change_events_candidate_profile_id'), table_name='identity_change_events')
    op.drop_index(op.f('ix_identity_change_events_anchor_id'), table_name='identity_change_events')
    op.drop_table('identity_change_events')
    # ### end Alembic commands ###
