"""sprint_19_osintgram

Revision ID: b4585c600b84
Revises: d32f5f3ebc79
Create Date: 2026-07-14 22:21:48.211728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b4585c600b84'
down_revision: Union[str, None] = 'd32f5f3ebc79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_provenance_observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('candidate_profile_id', sa.UUID(), nullable=False),
    sa.Column('discovery_run_id', sa.UUID(), nullable=False),
    sa.Column('connector_type', sa.String(length=64), nullable=False),
    sa.Column('connector_version', sa.String(length=64), nullable=False),
    sa.Column('capability', sa.String(length=64), nullable=False),
    sa.Column('input_alias_id', sa.UUID(), nullable=True),
    sa.Column('observation_type', sa.String(length=64), nullable=False),
    sa.Column('canonical_fact_key', sa.String(length=512), nullable=False),
    sa.Column('normalized_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_result_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['discovery_run_id'], ['candidate_discovery_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['input_alias_id'], ['identity_aliases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_provenance_observations_candidate_profile_id'), 'candidate_provenance_observations', ['candidate_profile_id'], unique=False)
    op.create_index(op.f('ix_candidate_provenance_observations_canonical_fact_key'), 'candidate_provenance_observations', ['canonical_fact_key'], unique=False)
    op.create_index(op.f('ix_candidate_provenance_observations_discovery_run_id'), 'candidate_provenance_observations', ['discovery_run_id'], unique=False)
    op.create_index(op.f('ix_candidate_provenance_observations_user_id'), 'candidate_provenance_observations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidate_provenance_observations_user_id'), table_name='candidate_provenance_observations')
    op.drop_index(op.f('ix_candidate_provenance_observations_discovery_run_id'), table_name='candidate_provenance_observations')
    op.drop_index(op.f('ix_candidate_provenance_observations_canonical_fact_key'), table_name='candidate_provenance_observations')
    op.drop_index(op.f('ix_candidate_provenance_observations_candidate_profile_id'), table_name='candidate_provenance_observations')
    op.drop_table('candidate_provenance_observations')
    # ### end Alembic commands ###
