"""Sprint 18 Enrichment and Clustering

Revision ID: d32f5f3ebc79
Revises: 524f042778ac
Create Date: 2026-07-14 22:03:20.796869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd32f5f3ebc79'
down_revision: Union[str, None] = '524f042778ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identity_cross_link_observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source_entity_id', sa.UUID(), nullable=False),
    sa.Column('source_entity_type', sa.String(length=32), nullable=False),
    sa.Column('target_entity_id', sa.UUID(), nullable=True),
    sa.Column('target_entity_type', sa.String(length=32), nullable=True),
    sa.Column('target_url_canonical', sa.String(length=2048), nullable=True),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('observation_source', sa.String(length=64), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_entity_id', 'target_url_canonical', name='uq_cross_link_observation')
    )
    op.create_index(op.f('ix_identity_cross_link_observations_source_entity_id'), 'identity_cross_link_observations', ['source_entity_id'], unique=False)
    op.create_index(op.f('ix_identity_cross_link_observations_target_entity_id'), 'identity_cross_link_observations', ['target_entity_id'], unique=False)
    op.create_index(op.f('ix_identity_cross_link_observations_target_url_canonical'), 'identity_cross_link_observations', ['target_url_canonical'], unique=False)
    op.create_index(op.f('ix_identity_cross_link_observations_user_id'), 'identity_cross_link_observations', ['user_id'], unique=False)
    op.create_table('identity_clusters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('anchor_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('cluster_version', sa.Integer(), nullable=False),
    sa.Column('policy_version', sa.Integer(), nullable=False),
    sa.Column('input_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['anchor_id'], ['identity_anchors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identity_clusters_anchor_id'), 'identity_clusters', ['anchor_id'], unique=False)
    op.create_index(op.f('ix_identity_clusters_user_id'), 'identity_clusters', ['user_id'], unique=False)
    op.create_table('identity_cluster_members',
    sa.Column('cluster_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cluster_id'], ['identity_clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cluster_id', 'candidate_id')
    )
    op.create_table('profile_visual_fingerprints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=True),
    sa.Column('confirmed_profile_id', sa.UUID(), nullable=True),
    sa.Column('exact_hash_sha256', sa.String(length=64), nullable=False),
    sa.Column('phash', sa.String(length=64), nullable=True),
    sa.Column('mime_type', sa.String(length=64), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('source_url_canonical', sa.String(length=2048), nullable=True),
    sa.Column('source_provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['confirmed_profile_id'], ['confirmed_profile_references.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_visual_fingerprints_candidate_id'), 'profile_visual_fingerprints', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_profile_visual_fingerprints_confirmed_profile_id'), 'profile_visual_fingerprints', ['confirmed_profile_id'], unique=False)
    op.create_index(op.f('ix_profile_visual_fingerprints_exact_hash_sha256'), 'profile_visual_fingerprints', ['exact_hash_sha256'], unique=False)
    op.create_index(op.f('ix_profile_visual_fingerprints_phash'), 'profile_visual_fingerprints', ['phash'], unique=False)
    op.create_index(op.f('ix_profile_visual_fingerprints_user_id'), 'profile_visual_fingerprints', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profile_visual_fingerprints_user_id'), table_name='profile_visual_fingerprints')
    op.drop_index(op.f('ix_profile_visual_fingerprints_phash'), table_name='profile_visual_fingerprints')
    op.drop_index(op.f('ix_profile_visual_fingerprints_exact_hash_sha256'), table_name='profile_visual_fingerprints')
    op.drop_index(op.f('ix_profile_visual_fingerprints_confirmed_profile_id'), table_name='profile_visual_fingerprints')
    op.drop_index(op.f('ix_profile_visual_fingerprints_candidate_id'), table_name='profile_visual_fingerprints')
    op.drop_table('profile_visual_fingerprints')
    op.drop_table('identity_cluster_members')
    op.drop_index(op.f('ix_identity_clusters_user_id'), table_name='identity_clusters')
    op.drop_index(op.f('ix_identity_clusters_anchor_id'), table_name='identity_clusters')
    op.drop_table('identity_clusters')
    op.drop_index(op.f('ix_identity_cross_link_observations_user_id'), table_name='identity_cross_link_observations')
    op.drop_index(op.f('ix_identity_cross_link_observations_target_url_canonical'), table_name='identity_cross_link_observations')
    op.drop_index(op.f('ix_identity_cross_link_observations_target_entity_id'), table_name='identity_cross_link_observations')
    op.drop_index(op.f('ix_identity_cross_link_observations_source_entity_id'), table_name='identity_cross_link_observations')
    op.drop_table('identity_cross_link_observations')
    # ### end Alembic commands ###
