"""discovery_run_orchestration_link

Revision ID: e6b4864fff3d
Revises: 11cf1eaeb4ad
Create Date: 2026-07-14 22:42:46.935577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6b4864fff3d'
down_revision: Union[str, None] = '11cf1eaeb4ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_discovery_runs', sa.Column('orchestration_run_id', sa.UUID(), nullable=True))
    op.add_column('candidate_discovery_runs', sa.Column('plan_item_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_candidate_discovery_runs_orchestration_run_id'), 'candidate_discovery_runs', ['orchestration_run_id'], unique=False)
    op.create_index(op.f('ix_candidate_discovery_runs_plan_item_id'), 'candidate_discovery_runs', ['plan_item_id'], unique=False)
    op.create_foreign_key(None, 'candidate_discovery_runs', 'identity_orchestration_runs', ['orchestration_run_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'candidate_discovery_runs', 'connector_execution_plan_items', ['plan_item_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'candidate_discovery_runs', type_='foreignkey')
    op.drop_constraint(None, 'candidate_discovery_runs', type_='foreignkey')
    op.drop_index(op.f('ix_candidate_discovery_runs_plan_item_id'), table_name='candidate_discovery_runs')
    op.drop_index(op.f('ix_candidate_discovery_runs_orchestration_run_id'), table_name='candidate_discovery_runs')
    op.drop_column('candidate_discovery_runs', 'plan_item_id')
    op.drop_column('candidate_discovery_runs', 'orchestration_run_id')
    # ### end Alembic commands ###
