"""Right-to-know / deletion / complaint letter generators (AIDR know + complaints lineage)."""
from __future__ import annotations

from datetime import UTC, datetime, timedelta
from typing import Any


def generate_right_to_know(
    *,
    regime: str,
    full_name: str,
    email: str,
    recipient_name: str,
    include_deletion: bool = True,
) -> dict[str, Any]:
    regime = regime.lower()
    if regime == "gdpr":
        subject = f"Subject Access Request (GDPR Art. 15) — {full_name}"
        rights = (
            "I am making a subject access request under Article 15 of the GDPR. "
            "Please confirm whether you process my personal data and provide a copy of all "
            "personal data you hold about me, the purposes, categories, recipients, and retention."
        )
        deletion = (
            "\n\nI also request erasure under Article 17 GDPR of all personal data you hold about me, "
            "except where a lawful exemption applies. Please confirm completion within one month."
            if include_deletion
            else ""
        )
        deadline_days = 30
    else:
        subject = f"California Consumer Privacy Act Request — {full_name}"
        rights = (
            "I am a consumer submitting a request under the California Consumer Privacy Act (CCPA/CPRA). "
            "Please disclose the categories and specific pieces of personal information you have collected "
            "about me, sources, business/commercial purposes, and third parties with whom it was shared/sold."
        )
        deletion = (
            "\n\nI also request deletion of my personal information under CCPA/CPRA, and that you "
            "direct service providers to delete my information where required. "
            "Please confirm within 45 days (extendable as permitted by law)."
            if include_deletion
            else ""
        )
        deadline_days = 45

    body = f"""{recipient_name}

{rights}{deletion}

Identifiers to locate my records:
- Full name: {full_name}
- Email: {email}

Please respond to: {email}

Sincerely,
{full_name}
Generated by DigiZafe (user-directed). Templates inspired by AIDR right-to-know lineage.
"""
    deadline = datetime.now(UTC) + timedelta(days=deadline_days)
    return {
        "subject": subject,
        "body": body.strip(),
        "deadline_at": deadline,
        "meta": {"regime": regime, "deadline_days": deadline_days, "aidr_lineage": "lib/right-to-know.js"},
    }


def generate_complaint(
    *,
    regime: str,
    full_name: str,
    email: str,
    recipient_name: str,
    regulator: str,
    facts: str,
) -> dict[str, Any]:
    if regulator == "ico":
        subject = f"Complaint regarding data controller {recipient_name} — {full_name}"
        intro = "I wish to raise a complaint with the Information Commissioner's Office regarding the following."
    else:
        subject = f"CCPA complaint — failure to respond by {recipient_name}"
        intro = (
            "I am submitting a complaint regarding a business's failure to timely respond to my "
            "CCPA/CPRA consumer request."
        )
    body = f"""{intro}

Consumer: {full_name}
Contact email: {email}
Business / broker: {recipient_name}

Facts:
{facts}

I request that the regulator investigate and require the business to comply with applicable privacy law.

Sincerely,
{full_name}
Generated by DigiZafe (user-directed). Templates inspired by AIDR complaints lineage.
"""
    return {
        "subject": subject,
        "body": body.strip(),
        "deadline_at": None,
        "meta": {"regime": regime, "regulator": regulator, "aidr_lineage": "lib/complaints"},
    }
